language: node_js
node_js:
    - stable
script:
    - yarn build
    - yarn lint
    - yarn test
deploy:
    provider: npm
    email: $NPM_AUTH_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
        branch: master
